# 开发环境的配置文件，在manage.py中声明


"""
Django settings for meiduo_mall project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os, sys     # 早期dirs列表设置模板路径用os.path.join()
from pathlib import Path

# 查看导包路径
# print(sys.path)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# 注意：本文件路径为meiduo_mall/meiduo_mall/settings/dev.py
BASE_DIR = Path(__file__).resolve().parent.parent                     # BASE_DIR指向 meiduo_mall/meiduo_mall/
# BASE_DIR = Path(__file__).resolve().parent.parent.parent            # BASE_DIR指向 meiduo_mall/
# print(__file__)
# print(Path(__file__))
# print(Path(__file__).resolve())                                    # 这三个输出结果均是 F:\Django\bookmanager\bookmanager\settings.py
# print(Path(__file__).resolve().parent)                             # F:\Django\bookmanager\bookmanager
# print(BASE_DIR)                                                    # F:\Django\bookmanager
# 早期版本如下
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# 其中__file__表示本文件setting.py文件名
# abspath(__file__)获取本文件绝对路径 F:\Django\bookmanager\bookmanager\settings.py
# dirname获取本文件所在文件夹(目录)路径 F:\Django\bookmanager\bookmanager 即获取父级目录
# 外层dirname再取上上级文件夹路径 F:\Django\bookmanager 即是BASE_DIR



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--h#-v9pv2gjo+)ttwk^um9&1cl!+r*5@2hu_f@qicg152#(lvu'

# 开发者调试用，部署上线后则改为False
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# 允许访问后端的主机列表，默认为空仅支持本机访问
# 安全机制：只能以列举的主机进行访问
# 改变允许方式：加入ip或者域名
# 此时默认的localhost和127.0.0.1访问需要命令行添加参数访问 python manage.py runserver 127.0.0.1:8000
ALLOWED_HOSTS = ['localhost',
                 '127.0.0.1',
                 '192.168.0.103',
                 ]

# sys.path.insert(0,os.path.join(BASE_DIR.parent,'abc'))      测试包abc里放人子应用
# sys.path.insert(0,os.path.join(BASE_DIR,'apps'))       # 与将apps标记为源根作用相同
# Application definition
# 安装注册子应用
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 注册子应用
    # 所有子应用都在包apps中，必须将包apps标记为源根，或者sys.path.insert()插入路径
    'meiduo_mall.apps.users',
    # 'users',
    # 'users.apps.UsersConfig',            # 此子应用在工程的meiduo_mall.apps中
    'huang',                               # 此子应用在工程的abc中， 用来测试


]


# 中间件
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# 此工程的URL配置入口，默认是工程名.urls  可修改但一般不改
ROOT_URLCONF = 'meiduo_mall.urls'


# 模板配置
TEMPLATES = [
    # jinja2模板引擎
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',          # jinja2 引擎
        # 此处的BASE_DIR指的是本工程里的meiduo_mall，而非工程本身的meiduo_mall
        'DIRS': [BASE_DIR / 'templates'],                             # 模板文件加载路径
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # 补充jinja2引擎环境
            'environment': 'meiduo_mall.utils.jinja2_env.environment',
        },
    },

    # 默认模板引擎
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },

]


WSGI_APPLICATION = 'meiduo_mall.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
# sqlite是一个嵌入式小型关系型数据库,主要是在移动端使用
# 中型数据库：mysql(甲骨文) sqlserver(微软)
# 大型数据库：oracle DB2
DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',

        'ENGINE': 'django.db.backends.mysql',
        'HOST': '192.168.94.131',
        'PORT': '3306',
        'USER': 'huangzhen',
        'PASSWORD': 'root',
        'NAME': 'meiduo',

    }
}

# session数据的存储方式可以如下:
# 方式一：Django对session的默认存储方式，可不写
# SESSION_ENGINE='django.contrib.sessions.backends.db'
# 方式二：设置为本地缓存：储存在本机内存中，如果丢失则不能找回，比数据库的方式读写更快
# SESSION_ENGINE='django.contrib.sessions.backends.cache'
# 方式三：设置为混合存储：优先从本机内存中存取，如果没有则从数据库中存取
# SESSION_ENGINE='django.contrib.sessions.backends.cached_db'
# 方式四：设置为redis存储：以后session不再保存在系统django_session表中，而是保存在redis库
CACHES = {
    # 默认存储在0号库
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",                    # 去找中间件
        # "LOCATION": "redis://127.0.0.1:6379/0",                      # 本机redis的0号库
        "LOCATION": "redis://192.168.94.131:6379/0",                   # 远程redis的0号库
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },

    # session存储在1号库
    "session": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://192.168.94.131:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },

    # 验证码存储在2号库
    "verify_code": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://192.168.94.131:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
}
# 以上进行了分库存储操作
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "session"


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# 语言设置
# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-Hans'

# 时区
# TIME_ZONE = 'UTC'    # 格林尼治时间
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
# Django是通过STATIC_URL区分动态资源和静态资源
# Django认定：请求资源http://ip:port + STATIC_URL + 文件名 为静态资源
# 即STATIC_URL规定是否是静态资源
STATIC_URL = '/static/'

# 告知系统静态文件加载路径，目前开发环境放在工程中，部署上线则放在Nginx代理服务器
STATICFILES_DIRS = [
    BASE_DIR / 'static',             # os.path.join(BASE_DIR, 'static')
]



# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# 日志配置信息
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # 是否禁用已经存在的日志器
    'formatters': {                            # 日志信息显示的格式
        'verbose': {                           # 描述详细
            'format': '%(levelname)s %(asctime)s %(module)s %(lineno)d %(message)s'
        },
        'simple': {                            # 描述简单
            'format': '%(levelname)s %(module)s %(lineno)d %(message)s'
        },
    },
    'filters': {                               # 对日志进行过滤
        'require_debug_true': {                # django在debug模式下才输出日志
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {                             # 日志处理方法
        'console': {                          # 向终端中输出日志
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {                            # 向文件中输出日志
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            # 'filename': os.path.join(os.path.dirname(BASE_DIR), 'logs/meiduo.log'),
            'filename': BASE_DIR.parent / 'logs/meiduo.log',                                     # 日志文件的位置
            'maxBytes': 300 * 1024 * 1024,
            'backupCount': 10,
            'formatter': 'verbose'
        },
    },
    'loggers': {                                       # 日志器
        'django': {                                    # 定义了一个名为django的日志器
            'handlers': ['console', 'file'],           # 可以同时向终端与文件中输出日志
            'propagate': True,                         # 是否继续传递日志信息
            'level': 'INFO',                            # 日志器接收的最低日志级别
        },
    }
}
